import '../models/books.dart';

List<Book> getBooksByType(Category category) {
  List<Book> allBooks = getAllBooks();
  return allBooks.where((book) => book.category == category).toList();
}

List<Book> getBooksByPurchased() {
  List<Book> allBooks = getAllBooks();
  return allBooks.where((book) => book.isPurchased == true).toList();
}

List<Book> getBooksByFree() {
  List<Book> allBooks = getAllBooks();
  return allBooks.where((book) => book.isPurchased == true).toList();
}

List<Book> getBooksByOpenPage(int page) {
  List<Book> allBooks = getAllBooks();
  return allBooks.where((book) => book.lastOpenPage >= page).toList();
}

List<Book> getAllBooks() {
  return [
    Book(
      title: 'KLONLAMA UYGULAMALARI VE BİYOETİK',
      category: Category.science,
      isbn: '9780140174922',
      price: 0,
      isFree: true,
      isPurchased: false,
      description:
          'Biyoetiksel bir şekilde canlıların klonlanması hakkında eşsiz bir araştırma.',
      rating: 5,
      yearRelease: 2024,
      pages: 38,
      authorName: 'Fatma Elmusa',
      imageUrl:
          'https://dergipark.org.tr/media/cache/issue_cover_filter/356f/234b/8909/6605c8281f859.jpg',
      lastOpenPage: 50,
      totalXP: 100,
    ),
    Book(
      title: 'Harry Potter Chamber Secrets',
      category: Category.comics,
      isbn: '9780307887894',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description:
          'Sırlar Odası, Muggle doğumlu öğrencileri temizlemek için yapılan bir Basiliske ev sahipliği yapıyordu. Oda, oyma ahşap sütunlarla çevrili ve en uçta Salazar Slytherinin heykeli bulunuyordu.',
      rating: 4.8,
      pages: 336,
      yearRelease: 2020,
      authorName: 'J.K. Rowling',
      imageUrl:
          'https://m.media-amazon.com/images/I/51mFoFmu0EL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 240,
    ),
    Book(
      category: Category.comics,
      price: 0.00,
      isFree: true,
      isPurchased: false,
      yearRelease: 1943,
      imageUrl:
          'https://upload.wikimedia.org/wikipedia/tr/thumb/f/f5/Kucukprens.jpg/1200px-Kucukprens.jpg',
      lastOpenPage: 0,
      totalXP: 198,
      title: 'Küçük Prens',
      isbn: '9781577314806',
      authorName: 'Antoine de Saint-Exupéry',
      description:
          'Yazar, uçağı bozulunca Sahrada Küçük Prensle karşılaşır. Prens, B-612deki gülü için gezegenler arası yolculuk yapar.',
      rating: 4.6,
      pages: 107,
    ),
    Book(
      title: 'Sefiller',
      category: Category.philosophy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description:
          'Sefiller, Jean Valjeanın dramını ve toplumsal eleştirileri içeren Victor Hugonun önemli bir eseridir. Romantizm akımını yansıtarak dönemin Fransasındaki adaletsizlik ve insanlık sorunlarını işler.',
      rating: 4.8,
      yearRelease: 1862,
      pages: 1900,
      authorName: 'Victor Hugo',
      imageUrl:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ebcosette.jpg/220px-Ebcosette.jpg',
      lastOpenPage: 0,
      totalXP: 500,
    ),
    Book(
      title: 'Sol Ayağım',
      category: Category.philosophy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: '',
      rating: 3.8,
      yearRelease: 1954,
      pages: 300,
      authorName: 'Christy Brown',
      imageUrl:
          'https://i.dr.com.tr/cache/500x400-0/originals/0001716966001-1.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 6',
      category: Category.cooking,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51VC+Vru96L._SY344_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 7',
      category: Category.history,
      isbn: '987654321',
      price: 0.00,
      isFree: true,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41ZLnc34EiL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 8',
      category: Category.philosophy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/416vxEWfI6L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 9',
      category: Category.science,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51CLYm-FruL._SX320_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 9',
      category: Category.technology,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51CLYm-FruL._SX320_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 10',
      category: Category.travel,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51B7kuFwQFL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 11',
      category: Category.children,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41UG6tNeHBL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 12',
      category: Category.mystery,
      isbn: '987654321',
      price: 0.00,
      isFree: true,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41pehfGTI5L._SX311_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 13',
      category: Category.selfHelp,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41HvCijjVbL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 14',
      category: Category.romance,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41x4eg5KyGL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 15',
      category: Category.religion,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41zWWzbiHpL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 16',
      category: Category.romance,
      isbn: '987654321',
      price: 0.00,
      isFree: true,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51yfA5Mo1hL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 17',
      category: Category.science,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41pTqRlersL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 18',
      category: Category.fantasy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41hE3aJ7C0L._SX311_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 19',
      category: Category.fantasy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41Y8Fw7UhQL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 20',
      category: Category.artAndLit,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: true,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41ORbvdT5ZL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 21',
      category: Category.business,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/4120mVtteHL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 22',
      category: Category.history,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: true,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41a2cF5TwUL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 23',
      category: Category.philosophy,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: false,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41tseIR-CSL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 24',
      category: Category.religion,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: true,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/51qtraYnQOL._SX311_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
    Book(
      title: 'Book 25',
      category: Category.selfHelp,
      isbn: '987654321',
      price: 12.99,
      isFree: false,
      isPurchased: true,
      description: 'Description of Book 2',
      rating: 3.8,
      yearRelease: 2020,
      pages: 300,
      authorName: 'Author 2',
      imageUrl:
          'https://m.media-amazon.com/images/I/41+QqNWz2qL._SY344_BO1,204,203,200_.jpg',
      lastOpenPage: 0,
      totalXP: 0,
    ),
  ];
}
